### PR TITLE
lang: Ukrainian translation

### PR DESCRIPTION
**Pull request by CakesTwix**

### CODE REVIEW

**Comment by CakesTwix** [comment]
Hi, again)
Finally got this mod translated.
If you need anything else translated, let me know

**Comment by SpearAndFang** [comment]
Wow! Much appreciated!

**Comment by CakesTwix** [comment]
Why did you close PR?
I can certainly see that you've added a translation, but without authorship

**Comment by SpearAndFang** [comment]
I asked myself the same question. The truth is that git is not a part of my current workflow so I fumble around on github trying to do it correctly.

I will try again.  If it's any consolation, I did credit you in two different places on the modDB.

**Pull request merged**
